sunday-web:
  env_file: /home/vagrant/.env
  environment:
  - POSTGRES_DB=sunday
  build: ./sunday/www
  ports:
   - "8081:5000"
  links:
   - sunday-db:db
sunday-db:
  env_file: /home/vagrant/.env
  environment:
  - POSTGRES_DB=sunday
  build: ./sunday/db
  ports:
   - "2346:5432"
  volumes:
   - /var/lib/postgresql/sunday-data:/var/lib/postgresql/data
monday-web:
  build: ./monday/www
  ports:
   - "8082:5000"
tuesday-web:
  env_file: /home/vagrant/.env
  environment:
  - POSTGRES_DB=tuesday
  - POSTGRES_HOST=db
  build: ./tuesday/www
  ports:
   - "8080:5000"
  volumes:
  - /home/vagrant/tuesday/www/app:/www/app
  links:
   - tuesday-db:db
tuesday-db:
  env_file: /home/vagrant/.env
  environment:
  - POSTGRES_DB=tuesday
  build: ./tuesday/db
  ports:
   - "2345:5432"
  volumes:
   - /var/lib/postgresql/tuesday-data:/var/lib/postgresql/data  