# -*- mode: ruby -*-
# vi: set ft=ruby :

# ----------------------------------------------------------------------------- 
# Maybe the only variables that need changing between projects!
# ----------------------------------------------------------------------------- 
project = "past-sunday"
docker_repo = "stsilabs"

host_port = 8081
docker_port = 5000

container_root = "/home/vagrant"
docker_root = "/home/past"

# ----------------------------------------------------------------------------- 
# Derive some other variables
# ----------------------------------------------------------------------------- 
tag = docker_repo + "/" + project

# ----------------------------------------------------------------------------- 
# Configure the VM
# ----------------------------------------------------------------------------- 
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: docker_port, host: host_port
  config.vm.network "forwarded_port", guest: 5432, host: 2345

  config.vm.synced_folder ".", "#{container_root}"

  config.vm.provider "virtualbox" do |v|
    v.name = project
  end

  # https://github.com/Varying-Vagrant-Vagrants/VVV/issues/517
  config.vm.provision "fix-no-tty", type: "shell" do |s|
    s.privileged = false
    s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
  end

  config.vm.provision :docker do |d|
	d.images = ["redis:alpine"]
	d.build_image "/home/vagrant/www", args: "-t web"
  end

  # Install docker-compose
  #config.vm.provision "shell", inline: <<-EOC
  #  curl -L https://github.com/docker/compose/releases/download/1.6.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
  #	chmod +x /usr/local/bin/docker-compose
  #EOC
end
