from api.endpoints.root import Root
from api.endpoints.corpus_index import CorpusIndex
from api.endpoints.corpus_detail import CorpusDetail
from api.endpoints.document_index import DocumentIndex
from api.endpoints.document_detail import DocumentDetail
from api.endpoints.corpus_document_index import CorpusDocumentIndex
from api.endpoints.document_corpus_index import DocumentCorpusIndex
from api.endpoints.document_corpus_detail import DocumentCorpusDetail
from api.endpoints.document_closest import DocumentClosest
from api.endpoints.keyword import Keyword
from api.endpoints.rank_root import RankRoot
from api.endpoints.rank import Rank
